
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          UpAssist.Neos.News:
            - Main
            - Inspector
            - Modules
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        UpAssist.Neos.News: true
